#!/usr/bin/env bash
#Configure a new Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello world" | sudo tee /var/www/html/index
sed -i '24i\		rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
service nginx restart
