#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i "25i\		error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
service nginx restart
