#!/usr/bin/env bash
# This script debugs why nginx is not listening on port 80


rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
